name: MATLAB Tests and Packaging
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: Run MATLAB Tests
    strategy:
      matrix:
        release: ["R2023b", "R2024a"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.release }}
          products: Signal_Processing_Toolbox Statistics_and_Machine_Learning_Toolbox Text_Analytics_Toolbox
      - name: Run tests
        uses: matlab-actions/run-build@v2.2.1
        with:
          tasks: check test
      - name: Report results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: MATLAB Test Results
          path: 'results.xml'
          working-directory: 'artifacts'
          reporter: java-junit
      - name: Report coverage
        uses: 5monkeys/cobertura-action@master
        with:
          path: 'artifacts/coverage.xml'
          minimum_coverage: 80
          report_name: Coverage Report

  package:
    name: Package MATLAB Toolbox
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    env:
      VERSION: "4.1.1"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1.2.5
        with:
          release: R2023b
      - name: Package toolbox
        uses: matlab-actions/run-build@v1.1.3
        with:
          tasks: package("${{ env.VERSION }}")
      - name: Upload toolbox
        uses: actions/upload-artifact@v4.3.0
        with:
          name: 'MAG Data Visualization.mltbx'
          path: artifacts
          if-no-files-found: error
      - name: Create release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: v${{ env.VERSION }}
          artifacts: 'artifacts/MAG Data Visualization.mltbx'
          bodyFile: 'resources/release-notes.md'
